export const CHANGE_USER_EMAIL = "CHANGE_USER_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_VERIFICATION_PASSWORD = "CHANGE_VERIFICATION_PASSWORD";
export const SAVE_QUESTIONS = "SAVE_QUESTIONS ";
export const ADD_USER = "ADD_USER";
export const CREATE_RADIO_LIST = "CREATE_RADIO_LIST";
